services:
  postgres:
    container_name: postgres-sql-qapp
    image: postgres
    environment:
      POSTGRES_USER: username
      POSTGRES_PASSWORD: password
      PGDATA: /var/lib/postgresql/data
      POSTGRES_DB: quizz_app
    volumes:
      - postgres:/data/postgres
    ports:
      - 5433:5432
    networks:
      - spring-app
    restart: unless-stopped

networks:
  spring-app:
    driver: bridge

volumes:
  postgres:
    driver: local